### ISSUE TITLE
EmojiOne 4.0 support

### ISSUE THREAD

**Issue by Demivan** [joypixels/emojione#610]
EmojiOne 4.0 is live but this project does not support new added emojis yet.
Is this project being updated to 4.0?

**Comment by lubber-de** [comment]
Same question for 4.5 now :wink: 
the json-files and emoji-awesome.map are still 4.0

**Comment by caseyahenson** [comment]
This is fixed in the 5.0 release https://github.com/joypixels/emoji-toolkit/releases/tag/5.0.0.
