### ISSUE TITLE
How insert the emojione into a div without the text-area

### ISSUE THREAD

**Issue by winadv** [joypixels/emojione#626]
Hello, I have the small problem.
I would like to insert the emojione into a div without the text-area and that this button when clicked inserted the emoji into a particular div.
  
Ex.:  
<###div class='text'> :+1: :100:  </div###>
<###div class='button'>Insert Emojis </div###> 

Is there a possibility with this script?
Thank you very much in advance.
  =)

**Comment by mervick** [comment]
You can do that using emojionearea.
Live example https://jsfiddle.net/mervick/1v03Lqnu/3704/
