### ISSUE TITLE
Rock climber emoji style issue

### ISSUE THREAD

**Issue by walmsley** [joypixels/emojione#630]
The rock climber emoji should not be wearing gloves.

- Rock climbers do not use gloves when rock climbing, except in some cold weather variants of the sport like ice climbing. In the scenario depicted, it would be very strange to wear gloves.

- See every other emoji font: https://emojipedia.org/person-climbing/ in which no other climbers are wearing gloves.

Thanks! Hopefully this is the right place to be reporting graphic design concerns.

**Comment by caseyahenson** [comment]
@walmsley I've passed this along to our design team and I'd expect that our next release will contain a gloveless climber. Thank you for the input!
