### ISSUE TITLE
In emoji.json: missing diversity from ": man_red_haired:"

### ISSUE THREAD

**Issue by daneesv** [joypixels/emojione#631]
"diversities": ["1f468-1f3fb-1f9b0", ---->"1f468-1f3fc-1f9b0"<----, "1f468-1f3fd-1f9b0", "1f468-1f3fe-1f9b0", "1f468-1f3ff-1f9b0"]
--------------------------------------------------------
 "1f468-1f9b0": {
        "name": "man, red haired",
        "unicode_version": 11,
        "category": "people",
        "order": 1499,
        "display": 1,
        "shortname": ":man_red_haired:",
        "shortname_alternates": [],
        "ascii": [],
        "diversity": null,
        "diversities": ["1f468-1f3fb-1f9b0", "1f468-1f3fc-1f9b0", "1f468-1f3fd-1f9b0", "1f468-1f3fe-1f9b0", "1f468-1f3ff-1f9b0"],
        "gender": null,
        "genders": [],
        "code_points": {
            "base": "1f468-1f9b0",
            "fully_qualified": "1f468-200d-1f9b0",
            "non_fully_qualified": "1f468-200d-1f9b0",
            "output": "1f468-200d-1f9b0",
            "default_matches": ["1f468-200d-1f9b0", "1f468-1f9b0"],
            "greedy_matches": ["1f468-200d-1f9b0", "1f468-1f9b0"],
            "decimal": ""
        },
        "keywords": [""]
    },

**Comment by caseyahenson** [comment]
@daneesv Thank you for pointing this out! We'll get it fixed up and pushed out soon.

**Comment by caseyahenson** [comment]
This is fixed in the 5.0 release https://github.com/joypixels/emoji-toolkit/releases/tag/5.0.0.
