### ISSUE TITLE
Replace :D with :smile: instead of :smiley:

### ISSUE THREAD

**Issue by MightyCreak** [joypixels/emojione#635]
Riot.im uses emojione and the auto-replacement of ascii strings to emoji (i.e. `:)` becoming :slightly_smiling_face:).

I think `:D` should not be converted to :smiley: (`:smiley:`) but rather to :smile: (`:smile:`).
In all the apps I use (e.g. Riot, Github and Slack), :smiley: looks more like a "surprise" than a "it's funny".

And, actually, Slack uses `:smile:` for `:D`.
And it also seems more logical to replace `:D` with `:smile:`, since `:)` is replaced by `:slight_smile:` (no `y` in the end).

I've tried to change the code in order to propose a PR, but I'm unsure which file I should really change... Is it emoji.js?

**Comment by caseyahenson** [comment]
This is fixed in the 5.0 release https://github.com/joypixels/emoji-toolkit/releases/tag/5.0.0.
