### ISSUE TITLE
How to get a list of emojis

### ISSUE THREAD

**Issue by mrxandy** [joypixels/emojione#638]
Hi, Developer!
How to output a list of emojis? 
For example: https://www.emojicopy.com/
Thank You!

**Comment by caseyahenson** [comment]
@mrxandy you may want to start with the `emoji.json` file located at the top level of this directory. This file contains categories for grouping, sort order, as well as the required `output` code point which can be converted to unicode using a function like this: https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L335. See also https://github.com/emojione/emojione/blob/master/UPGRADE.md#json-files for more info on data within this file.

**Comment by mrxandy** [comment]
> @mrxandy您可能想要从`emoji.json`位于此目录顶层的文件开始。此文件包含分组，排序顺序的类别，以及`output`可使用以下函数转换为unicode 所需的代码点：[https](https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L335)：[//github.com/emojione/emojione/blob/master/lib/js/emojione .js＃L335](https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L335)。有关此文件中数据的更多信息，另请参阅https://github.com/emojione/emojione/blob/master/UPGRADE.md#json-files。

ok,Thank you.

**Comment by lubber-de** [comment]
[emoji.json](https://github.com/emojione/emojione/blob/master/emoji.json),
[emoji_strategy.json](https://github.com/emojione/emojione/blob/master/emoji_strategy.json) and
[emojione/lib/emojione-awesome/emojione-awesome.map.scss](https://github.com/emojione/emojione/blob/master/lib/emojione-awesome/_emojione-awesome.map.scss)

are unfortunately still outdated (4.0).
Any ideas when those will also be updated to 4.5? 😉

**Comment by caseyahenson** [comment]
@lubber-de since 4.5 was an EmojiOne artwork update only, emoji.json and emoji_strategy.json have no updates. They'll be updated in the coming months as we launch EmojiOne 5.0 which will sync with Emoji 12.0/Unicode 12.

I'll see about getting the emojione-awesome library updated, although it should have been done with our last release.

**Comment by lubber-de** [comment]
@caseyahenson Good to know , thanks for clarification. 🙂 👍🏻
