### ISSUE TITLE
Packagist is out of date

### ISSUE THREAD

**Issue by chrisdeeming** [joypixels/emojione#646]
https://packagist.org/packages/emojione/emojione

Still lists v4.0.0.

Ideally a webhook would be configured so that Packagist is updated automatically.

**Comment by chrisdeeming** [comment]
It is sorted now and now on 4.5.0.

Comments about a webhook still stand though. I suspect this only got updated due to Packagist's periodic updates.

Webhook information is here:
https://packagist.org/about#how-to-update-packages

**Comment by caseyahenson** [comment]
@chrisdeeming thank you! We'll be updating webhooks this week :)
