### ISSUE TITLE
Update emoji(-strategy).json and awesome.map to 4.5

### ISSUE THREAD

**Issue by lubber-de** [joypixels/emojione#648]
## Description
Please update the following files to 4.5
[emoji.json](https://github.com/emojione/emojione/blob/master/emoji.json),
[emoji_strategy.json](https://github.com/emojione/emojione/blob/master/emoji_strategy.json) and
[emojione/lib/emojione-awesome/emojione-awesome.map.scss](https://github.com/emojione/emojione/blob/master/lib/emojione-awesome/_emojione-awesome.map.scss)

They are unfortunately still 4.0. 😢 

Thanks and 👍 for all the great work you have done!

**Comment by caseyahenson** [comment]
@lubber-de these are current to Unicode/Emoji 11.0 and will not receive updates until the release of 5.0 (projected this June) to bring the data current to Unicode/Emoji 12.0. In general, our major version releases will include data updates for compatibility with Unicode releases (along with artwork updates), and our minor version releases will include only artwork updates.

That said, if you see anything missing definitely let us know!
