### ISSUE TITLE
Upgrade iOS library to 4.5

### ISSUE THREAD

**Issue by kensenjohn** [joypixels/emojione#649]
Hello Emojione Team,

Do you have an item in your roadmap to upgrade the iOS library to 4.5?
If yes, then please let us know when can we expect this to be updated?

We are currently using 3.1 and we really enjoy it. We were able to upgrade our backend (PHP) to 4.5 however we are not able to use all the emojis effectively because they are not all supported in the iOS library.

Warm Regards
Kensen.

**Comment by caseyahenson** [comment]
@kensenjohn we've just released an updated iOS repository (current to Unicode 11, JoyPixels 4.5) at [https://www.github.com/joypixels/emoji-toolkit-ios](https://www.github.com/joypixels/emoji-toolkit-ios) which will be our only iOS integration moving forward. Let us know if you run into any issues!
