### ISSUE TITLE
Missing genders

### ISSUE THREAD

**Issue by jbrecht** [joypixels/emojione#654]
Apologies if this is a misunderstanding, but I'm curious why, for example, 'woman astronaut' has a null gender in emoji.json? Upon inspection, it looks like perhaps gender is only given a value if the unicode for it includes the 'woman symbol' emoji (2640), but not if it includes the 'woman' emoji (1f469). (Presumably this also applies for the male equivalents.)

Shouldn't the gender value of 'woman astronaut' be '1f469' rather than null? Or is that a different category, apart from gender?

**Comment by caseyahenson** [comment]
@jbrecht this is a great catch, thank you for pointing it out. It does appear that the gender for codepoints without `2640` are not being correctly set in the emoji.json file. Woman Astronaut should have a `gender` value of `2640` (the base code point of the female sign). We'll make the adjustments and get this published as soon as possible.

**Comment by jbrecht** [comment]
Thanks @caseyahenson !

**Comment by caseyahenson** [comment]
This is fixed in the 5.0 release https://github.com/joypixels/emoji-toolkit/releases/tag/5.0.0.
