### ISSUE TITLE
joypixels stickers installation

### ISSUE THREAD

**Issue by BoumBam** [joypixels/emojione#659]
Hello,
I have searched long time on google and on www.joypixels.com the documentations about how to install emoji stickers but i can't found anything to help me to install joypixels stickers on my web site.

I would like to know, how could i do to install the joypixels stickers on my web site ?(Somethings like some CDN to inlcude them in my web site). 

I'm using your joypixels emoji on my web site and i have never seen something done with perfection(CONGRATULATIONS FOR YOUR GREAT WORK).

Thanks.

**Comment by caseyahenson** [comment]
Thank you for your kind words, @BoumBam! We do not serve our premium assets (including emoji SVGs, 512px+ PNGs, stickers, and animations) over public CDN. You may utilize premium assets on your website, within the bounds of our licensing terms https://www.joypixels.com/licenses/premium, by including the assets in your code base and referencing individual images relative to your project root. Hopefully this helps to guide you.
