### ISSUE TITLE
Missing skin tone modifiers for “🤝” (U+1F91D) and “🤼” (U+1F93C) 

### ISSUE THREAD

**Issue by Peque** [joypixels/emojione#660]
Skin tone modifiers for “🤝” (U+1F91D) and “🤼” (U+1F93C)  were removed (see https://github.com/joypixels/emojione/issues/443) because they did not have the “Emoji_Modifier_Base” property in emoji-data.txt from unicode.org in [version 4.0](http://www.unicode.org/Public/emoji/4.0/emoji-data.txt) nor [5.0](http://www.unicode.org/Public/emoji/5.0/emoji-data.txt).

However, they seem to have that property in version 12.0 now:

https://www.unicode.org/Public/emoji/12.0/emoji-data.txt

Should they have skin tone modifiers now?

**Comment by caseyahenson** [comment]
Handshake (u1f91d) is used in Emoji 12.0 as a component of diverse/gendered "holding hands" emoji codepoints, however, it still does not receive diversity as a standalone codepoint. People wrestling (u1f93c) is modified with gender to form men wrestling and women wrestling, however, still does not receive diversity.
